name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint_and_fmt:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with: { cache: true }

            - name: Lint files
              run: deno lint
            - name: Check formatting
              run: deno fmt --check

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with: { cache: true }

            - name: Run unit tests on Deno
              run: deno test --permit-no-files
